version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/measures
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  describe:
    run: r:latest analysis/report.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        cohort: output/pre_covid_*.png

  pre_covid:
    run: r:latest analysis/cohort_viewer.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        cohort: output/descriptive_*.png
